/// Declarative per-100 g composition of the built-in seed catalog foods.
///
/// Every value is copied from a USDA FoodData Central record (SR Legacy
/// 2018 or FNDDS 2017-2018) named by [SeedFoodComposition.fdcId]; nothing is
/// estimated. Generated by `tool/generate_seed_food_composition_table.dart`
/// from `tool/data/seed_food_sources.json` and the committed verbatim source
/// subsets. Educational prototype; values describe foods, not people.
library;

enum SeedCompositionSource {
  /// USDA FDC SR Legacy, April 2018.
  srLegacy2018,

  /// USDA FDC Survey (FNDDS 2017-2018), FDC release 2020-10-30.
  fndds20172018,
}

enum SeedCompositionMatch {
  /// Same food and preparation state.
  equivalent,

  /// Closest authoritative record; see [SeedFoodComposition.note].
  proxy,
}

class SeedFoodComposition {
  final SeedCompositionSource source;
  final int fdcId;
  final String sourceDescription;
  final SeedCompositionMatch match;
  final String? note;

  final double? energyKcal;
  final double? proteinG;
  final double? fatG;

  /// Carbohydrate by difference (includes dietary fibre) in both sources.
  final double? carbohydrateByDifferenceG;
  final double? fiberG;
  final double? sodiumMg;

  /// Reported by FNDDS only; the SR Legacy extract carries no water column.
  final double? waterG;

  const SeedFoodComposition({
    required this.source,
    required this.fdcId,
    required this.sourceDescription,
    required this.match,
    this.note,
    required this.energyKcal,
    required this.proteinG,
    required this.fatG,
    required this.carbohydrateByDifferenceG,
    required this.fiberG,
    required this.sodiumMg,
    required this.waterG,
  });

  String get sourceLabel => switch (source) {
    SeedCompositionSource.srLegacy2018 => 'USDA FDC SR Legacy (2018)',
    SeedCompositionSource.fndds20172018 => 'USDA FDC FNDDS 2017-2018',
  };

  /// Available carbohydrate (by difference − total fibre), only when both
  /// terms are reported; missing fibre is never assumed to be zero.
  double? get availableCarbohydrateG {
    final carbohydrate = carbohydrateByDifferenceG;
    final fiber = fiberG;
    if (carbohydrate == null || fiber == null) return null;
    final available = carbohydrate - fiber;
    if (available < -0.05) return null;
    return available < 0 ? 0.0 : available;
  }
}
