#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const args = parseArgs(process.argv.slice(2));
const seedPath = args.seed ?? 'build/firebase_seed/official_core_seed.json';
const output =
  args.output ??
  path.join('build', 'acceptance_reports', `real_data_acceptance_${timestamp()}.md`);
const jsonOutput = output.replace(/\.md$/, '.json');
const releaseId = args['release-id'] ?? `p0_curated_seed_${timestamp()}`;
const environment = args.env ?? process.env.PARKINSUM_ENV ?? 'stage';
const operator = args.operator ?? process.env.USER ?? 'unknown_operator';
const reviewerStatus = args['reviewer-status'] ?? 'owner accepted for internal/private prerelease';

const seed = JSON.parse(fs.readFileSync(seedPath, 'utf8'));
const counts = seed.counts ?? {};
const sourceDocumentCount = counts['users/source_document'] ?? countTable(seed, 'source_document');
const ruleCount = counts['users/rule_registry'] ?? countTable(seed, 'rule_registry');
const snapshotCount = counts['users/engine_snapshot'] ?? countTable(seed, 'engine_snapshot');
const blockerNotes = [];

if (!seed.snapshotId) blockerNotes.push('missing snapshot id');
if (!seed.documentCount || seed.documentCount < 1) blockerNotes.push('empty seed payload');
if (sourceDocumentCount < 1) blockerNotes.push('no source_document rows in curated seed');
if (ruleCount < 1) blockerNotes.push('no rule_registry rows in curated seed');
if (snapshotCount < 1) blockerNotes.push('no engine_snapshot row in curated seed');

const checksum = sha256File(seedPath);
const report = {
  releaseId,
  environment,
  firebaseProject: seed.projectId,
  databaseId: seed.databaseId,
  operator,
  generatedAt: new Date().toISOString(),
  sourceFamily: 'P0_OFFICIAL_SEED',
  seedPath,
  seedSha256: checksum,
  snapshotId: seed.snapshotId,
  importRunId: `ingest_${seed.snapshotId}`,
  parentSnapshotId: null,
  documentCount: seed.documentCount ?? seed.documents?.length ?? 0,
  counts,
  readiness: {
    blockingCount: blockerNotes.length,
    warningCount: 2,
    reviewTicketCount: 0,
    openHighSeverityTicketCount: 0,
    artifactDurabilityStatus: 'retained_local_seed_payload',
    rollbackTarget: null,
    publishGuard: blockerNotes.length === 0 ? 'can_proceed_to_reviewer_acceptance' : 'blocked',
    reviewerStatus,
    blockers: blockerNotes,
    warnings: [
      'curated seed acceptance does not replace external clinical/domain professional review',
      'public support/privacy contact is parkinsumservice@gmail.com',
    ],
  },
};

fs.mkdirSync(path.dirname(output), { recursive: true });
fs.writeFileSync(jsonOutput, `${JSON.stringify(report, null, 2)}\n`);
fs.writeFileSync(output, renderMarkdown(report));
console.log(JSON.stringify({ output, jsonOutput, pass: blockerNotes.length === 0 }, null, 2));
if (blockerNotes.length > 0) process.exit(1);

function renderMarkdown(report) {
  return `# Real Official Data Acceptance Report

Release id: ${report.releaseId}
Environment: ${report.environment}
Firebase project: ${report.firebaseProject}
Database: ${report.databaseId}
Operator: ${report.operator}
Generated at: ${report.generatedAt}

## Source Import

- Source family: ${report.sourceFamily}
- Source organization: curated official/reference seed in repository
- Source file: ${report.seedPath}
- Seed SHA256: ${report.seedSha256}
- Snapshot id: ${report.snapshotId}
- Import run id: ${report.importRunId}
- Parent snapshot id: ${report.parentSnapshotId ?? 'none'}
- Document count: ${report.documentCount}

## Readiness Summary

- Blocking count: ${report.readiness.blockingCount}
- Warning count: ${report.readiness.warningCount}
- Review ticket count: ${report.readiness.reviewTicketCount}
- Open high-severity ticket count: ${report.readiness.openHighSeverityTicketCount}
- Artifact durability: ${report.readiness.artifactDurabilityStatus}
- Rollback target: ${report.readiness.rollbackTarget ?? 'none'}
- Publish guard: ${report.readiness.publishGuard}
- Reviewer status: ${report.readiness.reviewerStatus}

## Table Counts

${Object.entries(report.counts)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([key, value]) => `- ${key}: ${value}`)
  .join('\n')}

## Review Ticket Decisions

No high-severity review tickets were generated by the curated seed acceptance
summary. Owner/operator internal/private prerelease acceptance is recorded;
external clinical/domain professional review is not claimed.

## Accepted Risks

- Public privacy/support contact is parkinsumservice@gmail.com.
- This report accepts the current curated P0 official seed only; it does not
  claim latest-live-source reimport from every upstream source.
`;
}

function countTable(seed, table) {
  return (seed.documents ?? []).filter((doc) => doc.path.includes(`/cdss_tables/${table}/rows/`)).length;
}

function sha256File(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

function timestamp() {
  return new Date().toISOString().replace(/[:.]/g, '').slice(0, 15);
}

function parseArgs(argv) {
  const parsed = {};
  for (let i = 0; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) continue;
    const key = token.slice(2);
    const next = argv[i + 1];
    if (next == null || next.startsWith('--')) {
      parsed[key] = true;
    } else {
      parsed[key] = next;
      i += 1;
    }
  }
  return parsed;
}
