import '../../domain/entities/cdss_records.dart';

/// 临床证据注册层：
/// - 只登记“可公开核验”的论文元数据，供规则解释和审计引用；
/// - 不把论文摘要或结论伪装成 food/drug 主事实值；
/// - 当前优先覆盖已进入规则 provenance 或高价值 PD 营养/吞咽交互证据。
final clinicalEvidenceSourceDocuments = <SourceDocumentRecord>[
  SourceDocumentRecord(
    sourceDocId: 'fda-dhivy-high-protein',
    sourceFamily: 'FDA_LABEL',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / DailyMed',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'Dhivy label food effect reference',
    originUrl: 'https://dailymed.nlm.nih.gov/dailymed/',
    publishedAt: DateTime(2024, 1, 1),
    effectiveAt: DateTime(2024, 1, 1),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'fda_dhivy_high_protein',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"High protein meal timing reference for levodopa rule."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'dailymed-carbidopa-levodopa-iron',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'Carbidopa/Levodopa iron interaction label reference',
    originUrl: 'https://dailymed.nlm.nih.gov/dailymed/',
    publishedAt: DateTime(2024, 1, 1),
    effectiveAt: DateTime(2024, 1, 1),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_carbidopa_levodopa_iron',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"Iron chelation interaction label reference."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'dailymed-azilect-tyramine',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'Azilect tyramine label reference',
    originUrl: 'https://dailymed.nlm.nih.gov/dailymed/',
    publishedAt: DateTime(2024, 1, 1),
    effectiveAt: DateTime(2024, 1, 1),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_azilect_tyramine',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"Rasagiline tyramine warning label reference."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'dailymed-xadago-tyramine',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'Xadago tyramine label reference',
    originUrl: 'https://dailymed.nlm.nih.gov/dailymed/',
    publishedAt: DateTime(2024, 1, 1),
    effectiveAt: DateTime(2024, 1, 1),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_xadago_tyramine',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"Safinamide tyramine warning label reference."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'dailymed-peg-thickener',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'PEG thickener incompatibility label reference',
    originUrl: 'https://dailymed.nlm.nih.gov/dailymed/',
    publishedAt: DateTime(2024, 1, 1),
    effectiveAt: DateTime(2024, 1, 1),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_peg_thickener',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"PEG and starch-based thickener incompatibility reference."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'dailymed-selegiline-tyramine',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'Selegiline tyramine warning label reference',
    originUrl:
        'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=c81e983b-455d-2e65-e053-2a95a90a3123',
    publishedAt: DateTime(2024, 5, 8),
    effectiveAt: DateTime(2024, 5, 8),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_selegiline_tyramine',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"Selegiline oral label notes rare hypertensive reactions with tyramine-containing foods at recommended dose."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'dailymed-pramipexole-food',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'Pramipexole food administration label reference',
    originUrl:
        'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=3f90971a-e005-4dd3-bb93-b09125ada3c8',
    publishedAt: DateTime(2025, 10, 1),
    effectiveAt: DateTime(2025, 10, 1),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_pramipexole_food',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"Pramipexole may be taken with or without food; taking with food may reduce nausea."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'dailymed-ropinirole-food',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'Ropinirole food administration label reference',
    originUrl:
        'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=35d90f6f-3116-4afa-be2d-b65c160e8ab3',
    publishedAt: DateTime(2025, 12, 1),
    effectiveAt: DateTime(2025, 12, 1),
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_ropinirole_food',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"Ropinirole may be taken with or without food; extended-release labeling notes food may reduce nausea."}',
  ),
  const SourceDocumentRecord(
    sourceDocId: 'dailymed-opicapone-food',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'ONGENTYS food timing label reference',
    originUrl:
        'https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?audience=consumer&setid=a511a531-112e-43f8-a43f-5334b0efe979',
    publishedAt: null,
    effectiveAt: null,
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_opicapone_food',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"ONGENTYS label states patients should not eat for 1 hour before and at least 1 hour after each dose."}',
  ),
  const SourceDocumentRecord(
    sourceDocId: 'dailymed-rotigotine-food',
    sourceFamily: 'DAILYMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'FDA / NLM',
    jurisdiction: 'US',
    docType: 'drug_label',
    title: 'NEUPRO meal-independent administration label reference',
    originUrl:
        'https://dailymed.nlm.nih.gov/dailymed/fda/fdaDrugXsl.cfm?setid=939e28c5-f3a9-42c0-9a2d-8d471d82a6e0',
    publishedAt: null,
    effectiveAt: null,
    language: 'en-US',
    licenseNote: 'Official label metadata reference for rule provenance.',
    checksum: 'dailymed_rotigotine_food',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"evidence_kind":"official_label","notes":"NEUPRO label states food is not expected to affect absorption and the patch may be applied irrespective of meals."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'ann-pharmacother-enteral-levodopa',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Annals of Pharmacotherapy',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title: 'Interaction between levodopa and enteral nutrition',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/18272698/',
    publishedAt: DateTime(2008, 3, 1),
    effectiveAt: DateTime(2008, 3, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; do not treat article text as food composition data.',
    checksum: 'pmid_18272698',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"18272698","doi":"10.1345/aph.1K450","publication":"Ann Pharmacother","evidence_kind":"case_report","notes":"Supports enteral feeding + levodopa escalation evidence."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-rasagiline-tyramine-16856145',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Movement Disorders',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Effects of tyramine administration in Parkinson\'s disease patients treated with selective MAO-B inhibitor rasagiline',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/16856145/',
    publishedAt: DateTime(2006, 10, 1),
    effectiveAt: DateTime(2006, 10, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports provenance and audit, not primary label replacement.',
    checksum: 'pmid_16856145',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"16856145","doi":"10.1002/mds.21048","publication":"Mov Disord","evidence_kind":"clinical_trial","notes":"Supports rasagiline tyramine interaction evidence registration."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-enteral-levodopa-nmls-20628041',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Annals of Pharmacotherapy',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'An interaction between levodopa and enteral nutrition resulting in neuroleptic malignant-like syndrome and prolonged ICU stay',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/20628041/',
    publishedAt: DateTime(2010, 9, 1),
    effectiveAt: DateTime(2010, 9, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; use for evidence registry and audit trails.',
    checksum: 'pmid_20628041',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"20628041","doi":"10.1345/aph.1P242","publication":"Ann Pharmacother","evidence_kind":"case_report","notes":"Additional enteral feeding + levodopa escalation evidence."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-pd-nutrition-review-35730414',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Nutritional Neuroscience',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title: 'The role of nutrition on Parkinson\'s disease: a systematic review',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/35730414/',
    publishedAt: DateTime(2023, 7, 1),
    effectiveAt: DateTime(2023, 7, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; suitable for evidence/provenance, not nutrient fact ingestion.',
    checksum: 'pmid_35730414',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"35730414","doi":"10.1080/1028415X.2022.2073107","publication":"Nutr Neurosci","evidence_kind":"systematic_review","notes":"Useful high-level PD nutrition evidence registry entry."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-dysphagia-review-33201362',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Neurological Sciences',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Effectiveness of pharmacologic treatment for dysphagia in Parkinson\'s disease: a narrative review',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/33201362/',
    publishedAt: DateTime(2021, 2, 1),
    effectiveAt: DateTime(2021, 2, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports dysphagia-related clinical evidence referencing.',
    checksum: 'pmid_33201362',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"33201362","doi":"10.1007/s10072-020-04865-w","publication":"Neurol Sci","evidence_kind":"narrative_review","notes":"Useful for dysphagia caution/explanation provenance."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-constipation-review-27873359',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Movement Disorders',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Constipation in Parkinson\'s disease: Subjective symptoms, objective markers, and new perspectives',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/27873359/',
    publishedAt: DateTime(2017, 1, 1),
    effectiveAt: DateTime(2017, 1, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports constipation-related rule explanation and audit.',
    checksum: 'pmid_27873359',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"27873359","doi":"10.1002/mds.26866","publication":"Mov Disord","evidence_kind":"review","notes":"PD constipation review selected for evidence card layer."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-dysphagia-systematic-review-24794097',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Parkinsonism & Related Disorders',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Treatment effects for dysphagia in Parkinson\'s disease: a systematic review',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/24794097/',
    publishedAt: DateTime(2014, 8, 1),
    effectiveAt: DateTime(2014, 8, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports dysphagia treatment evidence cards and rule explanations.',
    checksum: 'pmid_24794097',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"24794097","doi":"10.1016/j.parkreldis.2014.03.026","publication":"Parkinsonism Relat Disord","evidence_kind":"systematic_review","notes":"Early dysphagia systematic review selected for evidence card layer."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-dysphagia-systematic-review-32526840',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization:
        'PubMed / International Journal of Environmental Research and Public Health',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Treatment of Dysphagia in Parkinson\'s Disease: A Systematic Review',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/32526840/',
    publishedAt: DateTime(2020, 6, 1),
    effectiveAt: DateTime(2020, 6, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports dysphagia caution cards and audit.',
    checksum: 'pmid_32526840',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"32526840","doi":"10.3390/ijerph17114104","publication":"Int J Environ Res Public Health","evidence_kind":"systematic_review","notes":"Updated dysphagia systematic review selected for evidence card layer."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-swallowing-behavioural-review-36951546',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization:
        'PubMed / International Journal of Language & Communication Disorders',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Behavioural interventions for swallowing in subjects with Parkinson\'s disease: A mixed methods systematic review',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/36951546/',
    publishedAt: DateTime(2023, 7, 1),
    effectiveAt: DateTime(2023, 7, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports behavioural swallowing intervention evidence cards.',
    checksum: 'pmid_36951546',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"36951546","doi":"10.1111/1460-6984.12865","publication":"Int J Lang Commun Disord","evidence_kind":"systematic_review","notes":"Behavioural swallowing intervention review selected for evidence card layer."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-probiotics-constipation-36439217',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Frontiers in Cellular and Infection Microbiology',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Probiotics for constipation in Parkinson\'s: A systematic review and meta-analysis of randomized controlled trials',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/36439217/',
    publishedAt: DateTime(2022, 11, 1),
    effectiveAt: DateTime(2022, 11, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports constipation intervention evidence cards.',
    checksum: 'pmid_36439217',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"36439217","doi":"10.3389/fcimb.2022.1038928","publication":"Front Cell Infect Microbiol","evidence_kind":"systematic_review_meta_analysis","notes":"Probiotic constipation intervention review selected for evidence card layer."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-dysphagia-meta-analysis-36546568',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Neurogastroenterology and Motility',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Dysphagia treatments in Parkinson\'s disease: A systematic review and meta-analysis',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/36546568/',
    publishedAt: DateTime(2023, 8, 1),
    effectiveAt: DateTime(2023, 8, 1),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports dysphagia treatment evidence cards and audit.',
    checksum: 'pmid_36546568',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"36546568","doi":"10.1111/nmo.14517","publication":"Neurogastroenterol Motil","evidence_kind":"systematic_review_meta_analysis","notes":"Additional high-value dysphagia treatment evidence card."}',
  ),
  SourceDocumentRecord(
    sourceDocId: 'pubmed-probiotics-meta-analysis-36703760',
    sourceFamily: 'PUBMED',
    dataTier: KnowledgeDataTier.p2,
    ingestionStrategy: SourceIngestionStrategy.clinicalEvidenceCard,
    organization: 'PubMed / Frontiers in Pharmacology',
    jurisdiction: 'GLOBAL',
    docType: 'journal_article',
    title:
        'Efficacy and safety of probiotics in Parkinson\'s constipation: A systematic review and meta-analysis',
    originUrl: 'https://pubmed.ncbi.nlm.nih.gov/36703760/',
    publishedAt: DateTime(2023, 1, 10),
    effectiveAt: DateTime(2023, 1, 10),
    language: 'en',
    licenseNote:
        'Bibliographic metadata only; supports constipation intervention evidence cards and audit.',
    checksum: 'pmid_36703760',
    sourceStatus: 'active_evidence',
    rawPayload:
        '{"pmid":"36703760","doi":"10.3389/fphar.2022.1007654","publication":"Front Pharmacol","evidence_kind":"systematic_review_meta_analysis","notes":"Additional constipation intervention evidence card."}',
  ),
];
