// GENERATED FILE - DO NOT EDIT BY HAND.
// Sources: tool/data/seed_food_sources.json, tool/data/usda_sr_legacy_seed_subset_2018.csv,
//   tool/data/fndds_2017_2018/food_seed_subset.csv, tool/data/fndds_2017_2018/food_nutrient_seed_subset.csv
// Regenerate: dart run tool/generate_seed_food_composition_table.dart

import '../../domain/entities/seed_food_composition.dart';

/// Per-100 g composition of seed catalog foods, copied from USDA FDC.
const Map<String, SeedFoodComposition> seedFoodCompositions = {
  'seed_white_rice': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168878,
    sourceDescription: 'Rice, white, long-grain, regular, enriched, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 130.0,
    proteinG: 2.69,
    fatG: 0.28,
    carbohydrateByDifferenceG: 28.17,
    fiberG: 0.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_brown_rice': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169704,
    sourceDescription:
        'Rice, brown, long-grain, cooked (Includes foods for USDA\'s Food Distribution Program)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 123.0,
    proteinG: 2.74,
    fatG: 0.97,
    carbohydrateByDifferenceG: 25.58,
    fiberG: 1.6,
    sodiumMg: 4.0,
    waterG: null,
  ),
  'seed_oatmeal': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173905,
    sourceDescription:
        'Cereals, oats, regular and quick, unenriched, cooked with water (includes boiling and microwaving), without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 71.0,
    proteinG: 2.54,
    fatG: 1.52,
    carbohydrateByDifferenceG: 12.0,
    fiberG: 1.7,
    sodiumMg: 4.0,
    waterG: null,
  ),
  'seed_bread_white': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174924,
    sourceDescription:
        'Bread, white, commercially prepared (includes soft bread crumbs)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 266.0,
    proteinG: 8.85,
    fatG: 3.33,
    carbohydrateByDifferenceG: 49.42,
    fiberG: 2.7,
    sodiumMg: 490.0,
    waterG: null,
  ),
  'seed_bread_whole_wheat': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172688,
    sourceDescription: 'Bread, whole-wheat, commercially prepared',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 252.0,
    proteinG: 12.45,
    fatG: 3.5,
    carbohydrateByDifferenceG: 42.71,
    fiberG: 6.0,
    sodiumMg: 455.0,
    waterG: null,
  ),
  'seed_pasta': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169737,
    sourceDescription: 'Pasta, cooked, enriched, without added salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 158.0,
    proteinG: 5.8,
    fatG: 0.93,
    carbohydrateByDifferenceG: 30.86,
    fiberG: 1.8,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_quinoa': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168917,
    sourceDescription: 'Quinoa, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 120.0,
    proteinG: 4.4,
    fatG: 1.92,
    carbohydrateByDifferenceG: 21.3,
    fiberG: 2.8,
    sodiumMg: 7.0,
    waterG: null,
  ),
  'seed_couscous': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169700,
    sourceDescription: 'Couscous, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 112.0,
    proteinG: 3.79,
    fatG: 0.16,
    carbohydrateByDifferenceG: 23.22,
    fiberG: 1.4,
    sodiumMg: 5.0,
    waterG: null,
  ),
  'seed_potato_boiled': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170440,
    sourceDescription:
        'Potatoes, boiled, cooked without skin, flesh, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 86.0,
    proteinG: 1.71,
    fatG: 0.1,
    carbohydrateByDifferenceG: 20.01,
    fiberG: 1.8,
    sodiumMg: 5.0,
    waterG: null,
  ),
  'seed_sweet_potato': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168483,
    sourceDescription:
        'Sweet potato, cooked, baked in skin, flesh, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 90.0,
    proteinG: 2.01,
    fatG: 0.15,
    carbohydrateByDifferenceG: 20.71,
    fiberG: 3.3,
    sodiumMg: 36.0,
    waterG: null,
  ),
  'seed_corn': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169999,
    sourceDescription:
        'Corn, sweet, yellow, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 96.0,
    proteinG: 3.41,
    fatG: 1.5,
    carbohydrateByDifferenceG: 20.98,
    fiberG: 2.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_congee': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1101639,
    sourceDescription: 'Congee',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 33.0,
    proteinG: 0.68,
    fatG: 0.07,
    carbohydrateByDifferenceG: 7.16,
    fiberG: 0.1,
    sodiumMg: 253.0,
    waterG: 91.26,
  ),
  'seed_chicken_breast': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171477,
    sourceDescription:
        'Chicken, broilers or fryers, breast, meat only, cooked, roasted',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 165.0,
    proteinG: 31.02,
    fatG: 3.57,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 74.0,
    waterG: null,
  ),
  'seed_chicken_thigh': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172388,
    sourceDescription:
        'Chicken, broilers or fryers, thigh, meat only, cooked, roasted',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 179.0,
    proteinG: 24.76,
    fatG: 8.15,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 106.0,
    waterG: null,
  ),
  'seed_pork_loin': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168233,
    sourceDescription:
        'Pork, fresh, loin, whole, separable lean only, cooked, roasted',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 209.0,
    proteinG: 28.62,
    fatG: 9.63,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 58.0,
    waterG: null,
  ),
  'seed_beef_lean': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171791,
    sourceDescription:
        'Beef, ground, 95% lean meat / 5% fat, patty, cooked, broiled',
    match: SeedCompositionMatch.proxy,
    note: 'Lean ground beef (95% lean), broiled patty.',
    energyKcal: 174.0,
    proteinG: 26.29,
    fatG: 6.8,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 65.0,
    waterG: null,
  ),
  'seed_lamb': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1098340,
    sourceDescription: 'Lamb, NS as to cut, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 292.0,
    proteinG: 24.32,
    fatG: 20.77,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 394.0,
    waterG: 53.28,
  ),
  'seed_salmon': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 175168,
    sourceDescription: 'Fish, salmon, Atlantic, farmed, cooked, dry heat',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 206.0,
    proteinG: 22.1,
    fatG: 12.35,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 61.0,
    waterG: null,
  ),
  'seed_tuna_canned': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173709,
    sourceDescription:
        'Fish, tuna, light, canned in water, drained solids (Includes foods for USDA\'s Food Distribution Program)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 86.0,
    proteinG: 19.44,
    fatG: 0.96,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 247.0,
    waterG: null,
  ),
  'seed_white_fish': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171956,
    sourceDescription: 'Fish, cod, Atlantic, cooked, dry heat',
    match: SeedCompositionMatch.proxy,
    note: 'Atlantic cod, the reference white fish.',
    energyKcal: 105.0,
    proteinG: 22.83,
    fatG: 0.86,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 78.0,
    waterG: null,
  ),
  'seed_shrimp': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 175180,
    sourceDescription: 'Crustaceans, shrimp, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 99.0,
    proteinG: 23.98,
    fatG: 0.28,
    carbohydrateByDifferenceG: 0.2,
    fiberG: null,
    sodiumMg: 111.0,
    waterG: null,
  ),
  'seed_egg_whole': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173424,
    sourceDescription: 'Egg, whole, cooked, hard-boiled',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 155.0,
    proteinG: 12.58,
    fatG: 10.61,
    carbohydrateByDifferenceG: 1.12,
    fiberG: 0.0,
    sodiumMg: 124.0,
    waterG: null,
  ),
  'seed_egg_white': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172183,
    sourceDescription: 'Egg, white, raw, fresh',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 52.0,
    proteinG: 10.9,
    fatG: 0.17,
    carbohydrateByDifferenceG: 0.73,
    fiberG: 0.0,
    sodiumMg: 166.0,
    waterG: null,
  ),
  'seed_tofu_firm': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172475,
    sourceDescription: 'Tofu, raw, firm, prepared with calcium sulfate',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 144.0,
    proteinG: 17.27,
    fatG: 8.72,
    carbohydrateByDifferenceG: 2.78,
    fiberG: 2.3,
    sodiumMg: 14.0,
    waterG: null,
  ),
  'seed_tempeh': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174272,
    sourceDescription: 'Tempeh',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 192.0,
    proteinG: 20.29,
    fatG: 10.8,
    carbohydrateByDifferenceG: 7.64,
    fiberG: null,
    sodiumMg: 9.0,
    waterG: null,
  ),
  'seed_lentils': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172421,
    sourceDescription: 'Lentils, mature seeds, cooked, boiled, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 116.0,
    proteinG: 9.02,
    fatG: 0.38,
    carbohydrateByDifferenceG: 20.13,
    fiberG: 7.9,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_chickpeas': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173757,
    sourceDescription:
        'Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 164.0,
    proteinG: 8.86,
    fatG: 2.59,
    carbohydrateByDifferenceG: 27.42,
    fiberG: 7.6,
    sodiumMg: 7.0,
    waterG: null,
  ),
  'seed_black_beans': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173735,
    sourceDescription:
        'Beans, black, mature seeds, cooked, boiled, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 132.0,
    proteinG: 8.86,
    fatG: 0.54,
    carbohydrateByDifferenceG: 23.71,
    fiberG: 8.7,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_kidney_beans': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173740,
    sourceDescription:
        'Beans, kidney, all types, mature seeds, cooked, boiled, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 127.0,
    proteinG: 8.67,
    fatG: 0.5,
    carbohydrateByDifferenceG: 22.8,
    fiberG: 6.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_edamame': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168411,
    sourceDescription: 'Edamame, frozen, prepared',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 121.0,
    proteinG: 11.91,
    fatG: 5.2,
    carbohydrateByDifferenceG: 8.91,
    fiberG: 5.2,
    sodiumMg: 6.0,
    waterG: null,
  ),
  'seed_peanut_butter': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174266,
    sourceDescription:
        'Peanut butter, smooth style, with salt (Includes foods for USDA\'s Food Distribution Program)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 598.0,
    proteinG: 22.21,
    fatG: 51.36,
    carbohydrateByDifferenceG: 22.31,
    fiberG: 5.0,
    sodiumMg: 426.0,
    waterG: null,
  ),
  'seed_milk_whole': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171265,
    sourceDescription: 'Milk, whole, 3.25% milkfat, with added vitamin D',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 61.0,
    proteinG: 3.15,
    fatG: 3.25,
    carbohydrateByDifferenceG: 4.8,
    fiberG: 0.0,
    sodiumMg: 43.0,
    waterG: null,
  ),
  'seed_milk_skim': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171269,
    sourceDescription:
        'Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 34.0,
    proteinG: 3.37,
    fatG: 0.08,
    carbohydrateByDifferenceG: 4.96,
    fiberG: 0.0,
    sodiumMg: 42.0,
    waterG: null,
  ),
  'seed_yogurt_plain': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171284,
    sourceDescription: 'Yogurt, plain, whole milk',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 61.0,
    proteinG: 3.47,
    fatG: 3.25,
    carbohydrateByDifferenceG: 4.66,
    fiberG: 0.0,
    sodiumMg: 46.0,
    waterG: null,
  ),
  'seed_greek_yogurt': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170894,
    sourceDescription:
        'Yogurt, Greek, plain, nonfat (Includes foods for USDA\'s Food Distribution Program)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 59.0,
    proteinG: 10.19,
    fatG: 0.39,
    carbohydrateByDifferenceG: 3.6,
    fiberG: 0.0,
    sodiumMg: 36.0,
    waterG: null,
  ),
  'seed_cheese_cheddar': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173414,
    sourceDescription:
        'Cheese, cheddar (Includes foods for USDA\'s Food Distribution Program)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 403.0,
    proteinG: 22.87,
    fatG: 33.31,
    carbohydrateByDifferenceG: 3.37,
    fiberG: 0.0,
    sodiumMg: 653.0,
    waterG: null,
  ),
  'seed_cottage_cheese': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172179,
    sourceDescription: 'Cheese, cottage, creamed, large or small curd',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 98.0,
    proteinG: 11.12,
    fatG: 4.3,
    carbohydrateByDifferenceG: 3.38,
    fiberG: 0.0,
    sodiumMg: 315.0,
    waterG: null,
  ),
  'seed_soy_milk': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 175215,
    sourceDescription:
        'Soymilk (all flavors), unsweetened, with added calcium, vitamins A and D',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 33.0,
    proteinG: 2.86,
    fatG: 1.61,
    carbohydrateByDifferenceG: 1.74,
    fiberG: 0.5,
    sodiumMg: 37.0,
    waterG: null,
  ),
  'seed_almond_milk': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174832,
    sourceDescription: 'Beverages, almond milk, unsweetened, shelf stable',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 15.0,
    proteinG: 0.4,
    fatG: 0.96,
    carbohydrateByDifferenceG: 1.31,
    fiberG: 0.2,
    sodiumMg: 72.0,
    waterG: null,
  ),
  'seed_broccoli': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169967,
    sourceDescription: 'Broccoli, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 35.0,
    proteinG: 2.38,
    fatG: 0.41,
    carbohydrateByDifferenceG: 7.18,
    fiberG: 3.3,
    sodiumMg: 41.0,
    waterG: null,
  ),
  'seed_carrot': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170394,
    sourceDescription: 'Carrots, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 35.0,
    proteinG: 0.76,
    fatG: 0.18,
    carbohydrateByDifferenceG: 8.22,
    fiberG: 3.0,
    sodiumMg: 58.0,
    waterG: null,
  ),
  'seed_spinach': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168463,
    sourceDescription: 'Spinach, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 23.0,
    proteinG: 2.97,
    fatG: 0.26,
    carbohydrateByDifferenceG: 3.75,
    fiberG: 2.4,
    sodiumMg: 70.0,
    waterG: null,
  ),
  'seed_kale': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169238,
    sourceDescription: 'Kale, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 36.0,
    proteinG: 2.94,
    fatG: 1.21,
    carbohydrateByDifferenceG: 5.3,
    fiberG: 4.0,
    sodiumMg: 16.0,
    waterG: null,
  ),
  'seed_lettuce': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169247,
    sourceDescription: 'Lettuce, cos or romaine, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 17.0,
    proteinG: 1.23,
    fatG: 0.3,
    carbohydrateByDifferenceG: 3.29,
    fiberG: 2.1,
    sodiumMg: 8.0,
    waterG: null,
  ),
  'seed_tomato': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170457,
    sourceDescription: 'Tomatoes, red, ripe, raw, year round average',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 18.0,
    proteinG: 0.88,
    fatG: 0.2,
    carbohydrateByDifferenceG: 3.89,
    fiberG: 1.2,
    sodiumMg: 5.0,
    waterG: null,
  ),
  'seed_cucumber': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168409,
    sourceDescription: 'Cucumber, with peel, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 15.0,
    proteinG: 0.65,
    fatG: 0.11,
    carbohydrateByDifferenceG: 3.63,
    fiberG: 0.5,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_zucchini': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169292,
    sourceDescription:
        'Squash, summer, zucchini, includes skin, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 15.0,
    proteinG: 1.14,
    fatG: 0.36,
    carbohydrateByDifferenceG: 2.69,
    fiberG: 1.0,
    sodiumMg: 3.0,
    waterG: null,
  ),
  'seed_bell_pepper': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170108,
    sourceDescription: 'Peppers, sweet, red, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 26.0,
    proteinG: 0.99,
    fatG: 0.3,
    carbohydrateByDifferenceG: 6.03,
    fiberG: 2.1,
    sodiumMg: 4.0,
    waterG: null,
  ),
  'seed_cabbage': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169976,
    sourceDescription: 'Cabbage, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 23.0,
    proteinG: 1.27,
    fatG: 0.06,
    carbohydrateByDifferenceG: 5.51,
    fiberG: 1.9,
    sodiumMg: 8.0,
    waterG: null,
  ),
  'seed_bok_choy': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170391,
    sourceDescription:
        'Cabbage, chinese (pak-choi), cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 12.0,
    proteinG: 1.56,
    fatG: 0.16,
    carbohydrateByDifferenceG: 1.78,
    fiberG: 1.0,
    sodiumMg: 34.0,
    waterG: null,
  ),
  'seed_eggplant': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169229,
    sourceDescription: 'Eggplant, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 35.0,
    proteinG: 0.83,
    fatG: 0.23,
    carbohydrateByDifferenceG: 8.73,
    fiberG: 2.5,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_mushroom': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169252,
    sourceDescription:
        'Mushrooms, white, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 28.0,
    proteinG: 2.17,
    fatG: 0.47,
    carbohydrateByDifferenceG: 5.29,
    fiberG: 2.2,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_onion': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170001,
    sourceDescription: 'Onions, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 44.0,
    proteinG: 1.36,
    fatG: 0.19,
    carbohydrateByDifferenceG: 10.15,
    fiberG: 1.4,
    sodiumMg: 3.0,
    waterG: null,
  ),
  'seed_garlic': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169230,
    sourceDescription: 'Garlic, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 149.0,
    proteinG: 6.36,
    fatG: 0.5,
    carbohydrateByDifferenceG: 33.06,
    fiberG: 2.1,
    sodiumMg: 17.0,
    waterG: null,
  ),
  'seed_avocado': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171705,
    sourceDescription: 'Avocados, raw, all commercial varieties',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 160.0,
    proteinG: 2.0,
    fatG: 14.66,
    carbohydrateByDifferenceG: 8.53,
    fiberG: 6.7,
    sodiumMg: 7.0,
    waterG: null,
  ),
  'seed_apple': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171688,
    sourceDescription:
        'Apples, raw, with skin (Includes foods for USDA\'s Food Distribution Program)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 52.0,
    proteinG: 0.26,
    fatG: 0.17,
    carbohydrateByDifferenceG: 13.81,
    fiberG: 2.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_banana': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173944,
    sourceDescription: 'Bananas, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 89.0,
    proteinG: 1.09,
    fatG: 0.33,
    carbohydrateByDifferenceG: 22.84,
    fiberG: 2.6,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_orange': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169097,
    sourceDescription: 'Oranges, raw, all commercial varieties',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 47.0,
    proteinG: 0.94,
    fatG: 0.12,
    carbohydrateByDifferenceG: 11.75,
    fiberG: 2.4,
    sodiumMg: 0.0,
    waterG: null,
  ),
  'seed_grapes': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174683,
    sourceDescription:
        'Grapes, red or green (European type, such as Thompson seedless), raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 69.0,
    proteinG: 0.72,
    fatG: 0.16,
    carbohydrateByDifferenceG: 18.1,
    fiberG: 0.9,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_strawberries': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 167762,
    sourceDescription: 'Strawberries, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 32.0,
    proteinG: 0.67,
    fatG: 0.3,
    carbohydrateByDifferenceG: 7.68,
    fiberG: 2.0,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_blueberries': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171711,
    sourceDescription: 'Blueberries, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 57.0,
    proteinG: 0.74,
    fatG: 0.33,
    carbohydrateByDifferenceG: 14.49,
    fiberG: 2.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_pear': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169118,
    sourceDescription: 'Pears, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 57.0,
    proteinG: 0.36,
    fatG: 0.14,
    carbohydrateByDifferenceG: 15.23,
    fiberG: 3.1,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_watermelon': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 167765,
    sourceDescription: 'Watermelon, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 30.0,
    proteinG: 0.61,
    fatG: 0.15,
    carbohydrateByDifferenceG: 7.55,
    fiberG: 0.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_mango': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169910,
    sourceDescription: 'Mangos, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 60.0,
    proteinG: 0.82,
    fatG: 0.38,
    carbohydrateByDifferenceG: 14.98,
    fiberG: 1.6,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_pineapple': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169124,
    sourceDescription: 'Pineapple, raw, all varieties',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 50.0,
    proteinG: 0.54,
    fatG: 0.12,
    carbohydrateByDifferenceG: 13.12,
    fiberG: 1.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_kiwi': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168153,
    sourceDescription: 'Kiwifruit, green, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 61.0,
    proteinG: 1.14,
    fatG: 0.52,
    carbohydrateByDifferenceG: 14.66,
    fiberG: 3.0,
    sodiumMg: 3.0,
    waterG: null,
  ),
  'seed_peach': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169928,
    sourceDescription: 'Peaches, yellow, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 39.0,
    proteinG: 0.91,
    fatG: 0.25,
    carbohydrateByDifferenceG: 9.54,
    fiberG: 1.5,
    sodiumMg: 0.0,
    waterG: null,
  ),
  'seed_olive_oil': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171413,
    sourceDescription: 'Oil, olive, salad or cooking',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 884.0,
    proteinG: 0.0,
    fatG: 100.0,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_butter': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173430,
    sourceDescription: 'Butter, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 717.0,
    proteinG: 0.85,
    fatG: 81.11,
    carbohydrateByDifferenceG: 0.06,
    fiberG: 0.0,
    sodiumMg: 11.0,
    waterG: null,
  ),
  'seed_almonds': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170567,
    sourceDescription: 'Nuts, almonds',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 579.0,
    proteinG: 21.15,
    fatG: 49.93,
    carbohydrateByDifferenceG: 21.55,
    fiberG: 12.5,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_walnuts': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170187,
    sourceDescription: 'Nuts, walnuts, english',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 654.0,
    proteinG: 15.23,
    fatG: 65.21,
    carbohydrateByDifferenceG: 13.71,
    fiberG: 6.7,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_chia_seeds': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170554,
    sourceDescription: 'Seeds, chia seeds, dried',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 486.0,
    proteinG: 16.54,
    fatG: 30.74,
    carbohydrateByDifferenceG: 42.12,
    fiberG: 34.4,
    sodiumMg: 16.0,
    waterG: null,
  ),
  'seed_water': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 175103,
    sourceDescription: 'Beverages, water, tap, municipal',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 0.0,
    proteinG: 0.0,
    fatG: 0.0,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 3.0,
    waterG: null,
  ),
  'seed_coffee_black': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171890,
    sourceDescription: 'Beverages, coffee, brewed, prepared with tap water',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 1.0,
    proteinG: 0.12,
    fatG: 0.02,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_tea_green': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171917,
    sourceDescription: 'Beverages, tea, green, brewed, regular',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 1.0,
    proteinG: 0.22,
    fatG: 0.0,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_tea_black': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173227,
    sourceDescription: 'Beverages, tea, black, brewed, prepared with tap water',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 1.0,
    proteinG: 0.0,
    fatG: 0.0,
    carbohydrateByDifferenceG: 0.3,
    fiberG: 0.0,
    sodiumMg: 3.0,
    waterG: null,
  ),
  'seed_orange_juice': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169098,
    sourceDescription:
        'Orange juice, raw (Includes foods for USDA\'s Food Distribution Program)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 45.0,
    proteinG: 0.7,
    fatG: 0.2,
    carbohydrateByDifferenceG: 10.4,
    fiberG: 0.2,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_apple_juice': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173933,
    sourceDescription:
        'Apple juice, canned or bottled, unsweetened, without added ascorbic acid',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 46.0,
    proteinG: 0.1,
    fatG: 0.13,
    carbohydrateByDifferenceG: 11.3,
    fiberG: 0.2,
    sodiumMg: 4.0,
    waterG: null,
  ),
  'seed_broth_chicken': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174536,
    sourceDescription: 'Soup, chicken broth, ready-to-serve',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 6.0,
    proteinG: 0.64,
    fatG: 0.21,
    carbohydrateByDifferenceG: 0.44,
    fiberG: 0.0,
    sodiumMg: 371.0,
    waterG: null,
  ),
  'seed_sandwich_turkey': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1099887,
    sourceDescription: 'Turkey sandwich, with spread',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 225.0,
    proteinG: 20.28,
    fatG: 7.03,
    carbohydrateByDifferenceG: 18.61,
    fiberG: 0.9,
    sodiumMg: 346.0,
    waterG: 52.76,
  ),
  'seed_pizza_cheese': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170317,
    sourceDescription: 'Pizza, cheese topping, regular crust, frozen, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 268.0,
    proteinG: 10.36,
    fatG: 12.28,
    carbohydrateByDifferenceG: 29.02,
    fiberG: 2.2,
    sodiumMg: 447.0,
    waterG: null,
  ),
  'seed_burger_beef': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170693,
    sourceDescription: 'Fast foods, hamburger; single, regular patty; plain',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 297.0,
    proteinG: 16.52,
    fatG: 12.01,
    carbohydrateByDifferenceG: 31.5,
    fiberG: 1.7,
    sodiumMg: 331.0,
    waterG: null,
  ),
  'seed_fries': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170698,
    sourceDescription: 'Fast foods, potato, french fried in vegetable oil',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 312.0,
    proteinG: 3.43,
    fatG: 14.73,
    carbohydrateByDifferenceG: 41.44,
    fiberG: 3.8,
    sodiumMg: 210.0,
    waterG: null,
  ),
  'seed_curry_chicken': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1099246,
    sourceDescription: 'Chicken curry',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 106.0,
    proteinG: 6.47,
    fatG: 6.45,
    carbohydrateByDifferenceG: 6.47,
    fiberG: 1.4,
    sodiumMg: 376.0,
    waterG: 79.11,
  ),
  'seed_miso_soup': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1100471,
    sourceDescription: 'Soybean soup, miso broth',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 33.0,
    proteinG: 2.47,
    fatG: 1.56,
    carbohydrateByDifferenceG: 2.47,
    fiberG: 0.4,
    sodiumMg: 610.0,
    waterG: 91.66,
  ),
  'seed_chocolate_dark': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170273,
    sourceDescription: 'Chocolate, dark, 70-85% cacao solids',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 598.0,
    proteinG: 7.79,
    fatG: 42.63,
    carbohydrateByDifferenceG: 45.9,
    fiberG: 10.9,
    sodiumMg: 20.0,
    waterG: null,
  ),
  'seed_ice_cream': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 167575,
    sourceDescription: 'Ice creams, vanilla',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 207.0,
    proteinG: 3.5,
    fatG: 11.0,
    carbohydrateByDifferenceG: 23.6,
    fiberG: 0.7,
    sodiumMg: 80.0,
    waterG: null,
  ),
  'seed_cn_jujube': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168152,
    sourceDescription: 'Jujube, Chinese, fresh, dried',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 281.0,
    proteinG: 4.72,
    fatG: 0.5,
    carbohydrateByDifferenceG: 72.52,
    fiberG: 6.0,
    sodiumMg: 5.0,
    waterG: null,
  ),
  'seed_cn_goji': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173032,
    sourceDescription: 'Goji berries, dried',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 349.0,
    proteinG: 14.26,
    fatG: 0.39,
    carbohydrateByDifferenceG: 77.06,
    fiberG: 13.0,
    sodiumMg: 298.0,
    waterG: null,
  ),
  'seed_cn_lotus_root': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168430,
    sourceDescription: 'Lotus root, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 66.0,
    proteinG: 1.58,
    fatG: 0.07,
    carbohydrateByDifferenceG: 16.02,
    fiberG: 3.1,
    sodiumMg: 45.0,
    waterG: null,
  ),
  'seed_cn_bamboo_shoots': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169210,
    sourceDescription: 'Bamboo shoots, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 27.0,
    proteinG: 2.6,
    fatG: 0.3,
    carbohydrateByDifferenceG: 5.2,
    fiberG: 2.2,
    sodiumMg: 4.0,
    waterG: null,
  ),
  'seed_cn_longan': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169089,
    sourceDescription: 'Longans, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 60.0,
    proteinG: 1.31,
    fatG: 0.1,
    carbohydrateByDifferenceG: 15.14,
    fiberG: 1.1,
    sodiumMg: 0.0,
    waterG: null,
  ),
  'seed_cn_lychee': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169086,
    sourceDescription: 'Litchis, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 66.0,
    proteinG: 0.83,
    fatG: 0.44,
    carbohydrateByDifferenceG: 16.53,
    fiberG: 1.3,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_cn_persimmon': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169941,
    sourceDescription: 'Persimmons, japanese, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 70.0,
    proteinG: 0.58,
    fatG: 0.19,
    carbohydrateByDifferenceG: 18.59,
    fiberG: 3.6,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_cn_bitter_melon': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168394,
    sourceDescription:
        'Balsam-pear (bitter gourd), pods, cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 19.0,
    proteinG: 0.84,
    fatG: 0.18,
    carbohydrateByDifferenceG: 4.32,
    fiberG: 2.0,
    sodiumMg: 6.0,
    waterG: null,
  ),
  'seed_cn_winter_melon': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170475,
    sourceDescription:
        'Waxgourd, (chinese preserving melon), cooked, boiled, drained, without salt',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 14.0,
    proteinG: 0.4,
    fatG: 0.2,
    carbohydrateByDifferenceG: 3.04,
    fiberG: 1.0,
    sodiumMg: 107.0,
    waterG: null,
  ),
  'seed_cn_bean_sprouts': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169957,
    sourceDescription: 'Mung beans, mature seeds, sprouted, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 30.0,
    proteinG: 3.04,
    fatG: 0.18,
    carbohydrateByDifferenceG: 5.94,
    fiberG: 1.8,
    sodiumMg: 6.0,
    waterG: null,
  ),
  'seed_jp_tai': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1098945,
    sourceDescription: 'Porgy, raw',
    match: SeedCompositionMatch.proxy,
    note:
        'Raw porgy (family Sparidae); Japanese red sea bream is not listed separately.',
    energyKcal: 105.0,
    proteinG: 18.88,
    fatG: 2.73,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 42.0,
    waterG: 75.37,
  ),
  'seed_jp_saba': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 175119,
    sourceDescription: 'Fish, mackerel, Atlantic, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 205.0,
    proteinG: 18.6,
    fatG: 13.89,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 90.0,
    waterG: null,
  ),
  'seed_jp_buri': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 175163,
    sourceDescription: 'Fish, yellowtail, mixed species, raw',
    match: SeedCompositionMatch.proxy,
    note:
        'Raw yellowtail, mixed species; farmed Japanese buri is usually fattier.',
    energyKcal: 146.0,
    proteinG: 23.14,
    fatG: 5.24,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 39.0,
    waterG: null,
  ),
  'seed_jp_natto': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172443,
    sourceDescription: 'Natto',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 211.0,
    proteinG: 19.4,
    fatG: 11.0,
    carbohydrateByDifferenceG: 12.68,
    fiberG: 5.4,
    sodiumMg: 7.0,
    waterG: null,
  ),
  'seed_jp_miso': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172442,
    sourceDescription: 'Miso',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 198.0,
    proteinG: 12.79,
    fatG: 6.01,
    carbohydrateByDifferenceG: 25.37,
    fiberG: 5.4,
    sodiumMg: 3728.0,
    waterG: null,
  ),
  'seed_jp_soy_sauce': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174277,
    sourceDescription: 'Soy sauce made from soy and wheat (shoyu)',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 53.0,
    proteinG: 8.14,
    fatG: 0.57,
    carbohydrateByDifferenceG: 4.93,
    fiberG: 0.8,
    sodiumMg: 5493.0,
    waterG: null,
  ),
  'seed_jp_kombu': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168457,
    sourceDescription: 'Seaweed, kelp, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 43.0,
    proteinG: 1.68,
    fatG: 0.56,
    carbohydrateByDifferenceG: 9.57,
    fiberG: 1.3,
    sodiumMg: 233.0,
    waterG: null,
  ),
  'seed_jp_wakame': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170496,
    sourceDescription: 'Seaweed, wakame, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 45.0,
    proteinG: 3.03,
    fatG: 0.64,
    carbohydrateByDifferenceG: 9.14,
    fiberG: 0.5,
    sodiumMg: 872.0,
    waterG: null,
  ),
  'seed_jp_daikon': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168451,
    sourceDescription: 'Radishes, oriental, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 18.0,
    proteinG: 0.6,
    fatG: 0.1,
    carbohydrateByDifferenceG: 4.1,
    fiberG: 1.6,
    sodiumMg: 21.0,
    waterG: null,
  ),
  'seed_jp_renkon': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169250,
    sourceDescription: 'Lotus root, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 74.0,
    proteinG: 2.6,
    fatG: 0.1,
    carbohydrateByDifferenceG: 17.23,
    fiberG: 4.9,
    sodiumMg: 40.0,
    waterG: null,
  ),
  'seed_jp_shiitake': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169242,
    sourceDescription: 'Mushrooms, shiitake, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 34.0,
    proteinG: 2.24,
    fatG: 0.49,
    carbohydrateByDifferenceG: 6.79,
    fiberG: 2.5,
    sodiumMg: 9.0,
    waterG: null,
  ),
  'seed_jp_gobo': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 169974,
    sourceDescription: 'Burdock root, raw',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 72.0,
    proteinG: 1.53,
    fatG: 0.15,
    carbohydrateByDifferenceG: 17.34,
    fiberG: 3.3,
    sodiumMg: 5.0,
    waterG: null,
  ),
  'seed_jp_soba': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168907,
    sourceDescription: 'Noodles, japanese, soba, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 99.0,
    proteinG: 5.06,
    fatG: 0.1,
    carbohydrateByDifferenceG: 21.44,
    fiberG: null,
    sodiumMg: 60.0,
    waterG: null,
  ),
  'seed_kr_kimchi': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170392,
    sourceDescription: 'Cabbage, kimchi',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 15.0,
    proteinG: 1.1,
    fatG: 0.5,
    carbohydrateByDifferenceG: 2.4,
    fiberG: 1.6,
    sodiumMg: 498.0,
    waterG: null,
  ),
  'seed_kr_miyeok': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1103724,
    sourceDescription: 'Seaweed soup',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 35.0,
    proteinG: 3.71,
    fatG: 1.37,
    carbohydrateByDifferenceG: 2.4,
    fiberG: 0.2,
    sodiumMg: 527.0,
    waterG: 89.97,
  ),
  'seed_kr_bibimbap': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1102335,
    sourceDescription: 'Bibimbap, Korean',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 80.0,
    proteinG: 5.47,
    fatG: 2.88,
    carbohydrateByDifferenceG: 8.61,
    fiberG: 1.1,
    sodiumMg: 424.0,
    waterG: 81.29,
  ),
  'seed_in_dal': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1100445,
    sourceDescription: 'Lentil curry',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 110.0,
    proteinG: 3.67,
    fatG: 5.61,
    carbohydrateByDifferenceG: 12.28,
    fiberG: 3.4,
    sodiumMg: 383.0,
    waterG: 76.73,
  ),
  'seed_in_chapati': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171844,
    sourceDescription: 'Bread, chapati or roti, plain, commercially prepared',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 297.0,
    proteinG: 11.25,
    fatG: 7.45,
    carbohydrateByDifferenceG: 46.36,
    fiberG: 4.9,
    sodiumMg: 409.0,
    waterG: null,
  ),
  'seed_in_naan': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 171845,
    sourceDescription:
        'Bread, naan, plain, commercially prepared, refrigerated',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 291.0,
    proteinG: 9.62,
    fatG: 5.65,
    carbohydrateByDifferenceG: 50.43,
    fiberG: 2.2,
    sodiumMg: 465.0,
    waterG: null,
  ),
  'seed_in_ghee': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173412,
    sourceDescription: 'Butter oil, anhydrous',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 876.0,
    proteinG: 0.28,
    fatG: 99.48,
    carbohydrateByDifferenceG: 0.0,
    fiberG: 0.0,
    sodiumMg: 2.0,
    waterG: null,
  ),
  'seed_in_basmati': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 168878,
    sourceDescription: 'Rice, white, long-grain, regular, enriched, cooked',
    match: SeedCompositionMatch.proxy,
    note: 'Long-grain white rice, cooked; basmati is not listed separately.',
    energyKcal: 130.0,
    proteinG: 2.69,
    fatG: 0.28,
    carbohydrateByDifferenceG: 28.17,
    fiberG: 0.4,
    sodiumMg: 1.0,
    waterG: null,
  ),
  'seed_in_dosa': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1101518,
    sourceDescription: 'Dosa (Indian), plain',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 210.0,
    proteinG: 5.7,
    fatG: 4.05,
    carbohydrateByDifferenceG: 37.04,
    fiberG: 1.8,
    sodiumMg: 309.0,
    waterG: 51.8,
  ),
  'seed_in_biryani': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1099366,
    sourceDescription: 'Biryani with chicken',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 103.0,
    proteinG: 7.15,
    fatG: 2.36,
    carbohydrateByDifferenceG: 13.57,
    fiberG: 1.1,
    sodiumMg: 162.0,
    waterG: 75.91,
  ),
  'seed_in_paratha': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1100746,
    sourceDescription: 'Bread, paratha, wheat',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 326.0,
    proteinG: 6.36,
    fatG: 13.2,
    carbohydrateByDifferenceG: 45.35,
    fiberG: 9.6,
    sodiumMg: 452.0,
    waterG: 33.5,
  ),
  'seed_med_hummus': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174289,
    sourceDescription: 'Hummus, commercial',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 237.0,
    proteinG: 7.78,
    fatG: 17.82,
    carbohydrateByDifferenceG: 15.0,
    fiberG: 5.5,
    sodiumMg: 426.0,
    waterG: null,
  ),
  'seed_med_falafel': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172455,
    sourceDescription: 'Falafel, home-prepared',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 333.0,
    proteinG: 13.31,
    fatG: 17.8,
    carbohydrateByDifferenceG: 31.84,
    fiberG: null,
    sodiumMg: 294.0,
    waterG: null,
  ),
  'seed_med_pita': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174915,
    sourceDescription: 'Bread, pita, white, enriched',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 275.0,
    proteinG: 9.1,
    fatG: 1.2,
    carbohydrateByDifferenceG: 55.7,
    fiberG: 2.2,
    sodiumMg: 536.0,
    waterG: null,
  ),
  'seed_med_tabbouleh': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1102520,
    sourceDescription: 'Tabbouleh',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 126.0,
    proteinG: 1.64,
    fatG: 9.66,
    carbohydrateByDifferenceG: 9.65,
    fiberG: 1.8,
    sodiumMg: 495.0,
    waterG: 77.32,
  ),
  'seed_med_baba_ganoush': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1103638,
    sourceDescription: 'Eggplant dip',
    match: SeedCompositionMatch.proxy,
    note: 'FNDDS \'Eggplant dip\'; recipes for baba ganoush vary.',
    energyKcal: 162.0,
    proteinG: 4.25,
    fatG: 13.25,
    carbohydrateByDifferenceG: 9.63,
    fiberG: 4.0,
    sodiumMg: 219.0,
    waterG: 70.84,
  ),
  'seed_med_tzatziki': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1097588,
    sourceDescription: 'Tzatziki dip',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 92.0,
    proteinG: 5.35,
    fatG: 6.31,
    carbohydrateByDifferenceG: 3.95,
    fiberG: 0.2,
    sodiumMg: 307.0,
    waterG: 83.08,
  ),
  'seed_med_feta': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 173420,
    sourceDescription: 'Cheese, feta',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 265.0,
    proteinG: 14.21,
    fatG: 21.49,
    carbohydrateByDifferenceG: 3.88,
    fiberG: 0.0,
    sodiumMg: 1139.0,
    waterG: null,
  ),
  'seed_med_olives': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1103678,
    sourceDescription: 'Olives, NFS',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 116.0,
    proteinG: 0.84,
    fatG: 10.9,
    carbohydrateByDifferenceG: 6.04,
    fiberG: 1.6,
    sodiumMg: 735.0,
    waterG: 79.99,
  ),
  'seed_med_dolma': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1102453,
    sourceDescription: 'Grape leaves stuffed with rice',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 166.0,
    proteinG: 2.28,
    fatG: 11.95,
    carbohydrateByDifferenceG: 13.88,
    fiberG: 3.1,
    sodiumMg: 166.0,
    waterG: 70.85,
  ),
  'seed_mx_tortilla_corn': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 175036,
    sourceDescription: 'Tortillas, ready-to-bake or -fry, corn',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 218.0,
    proteinG: 5.7,
    fatG: 2.85,
    carbohydrateByDifferenceG: 44.64,
    fiberG: 6.3,
    sodiumMg: 45.0,
    waterG: null,
  ),
  'seed_mx_refried_beans': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 172438,
    sourceDescription: 'Refried beans, canned, traditional style',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 90.0,
    proteinG: 4.98,
    fatG: 2.01,
    carbohydrateByDifferenceG: 13.55,
    fiberG: 3.7,
    sodiumMg: 370.0,
    waterG: null,
  ),
  'seed_mx_guacamole': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1102734,
    sourceDescription: 'Guacamole, NFS',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 155.0,
    proteinG: 1.95,
    fatG: 14.18,
    carbohydrateByDifferenceG: 8.45,
    fiberG: 6.5,
    sodiumMg: 344.0,
    waterG: 73.02,
  ),
  'seed_mx_salsa': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 174524,
    sourceDescription: 'Sauce, salsa, ready-to-serve',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 29.0,
    proteinG: 1.52,
    fatG: 0.17,
    carbohydrateByDifferenceG: 6.64,
    fiberG: 1.9,
    sodiumMg: 711.0,
    waterG: null,
  ),
  'seed_mx_tamale': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1101924,
    sourceDescription: 'Tamale with chicken',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 215.0,
    proteinG: 8.63,
    fatG: 13.69,
    carbohydrateByDifferenceG: 14.8,
    fiberG: 1.2,
    sodiumMg: 462.0,
    waterG: 61.27,
  ),
  'seed_mx_taco': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1101887,
    sourceDescription: 'Taco or tostada with meat',
    match: SeedCompositionMatch.proxy,
    note: 'FNDDS \'Taco or tostada with meat\' (meat not specified).',
    energyKcal: 247.0,
    proteinG: 10.47,
    fatG: 14.42,
    carbohydrateByDifferenceG: 19.23,
    fiberG: 2.7,
    sodiumMg: 536.0,
    waterG: 53.68,
  ),
  'seed_mx_quesadilla': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1101947,
    sourceDescription: 'Quesadilla, just cheese, meatless',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 345.0,
    proteinG: 12.74,
    fatG: 18.02,
    carbohydrateByDifferenceG: 32.48,
    fiberG: 2.3,
    sodiumMg: 680.0,
    waterG: 34.02,
  ),
  'seed_sea_pho': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1100099,
    sourceDescription: 'Pho',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 88.0,
    proteinG: 6.15,
    fatG: 2.26,
    carbohydrateByDifferenceG: 10.41,
    fiberG: 0.6,
    sodiumMg: 403.0,
    waterG: 79.89,
  ),
  'seed_sea_pad_thai': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1102188,
    sourceDescription: 'Pad Thai, NFS',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 154.0,
    proteinG: 8.14,
    fatG: 7.47,
    carbohydrateByDifferenceG: 14.37,
    fiberG: 1.2,
    sodiumMg: 385.0,
    waterG: 68.61,
  ),
  'seed_sea_sticky_rice': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1101643,
    sourceDescription: 'Rice, white, cooked, glutinous',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 96.0,
    proteinG: 2.01,
    fatG: 0.19,
    carbohydrateByDifferenceG: 20.97,
    fiberG: 1.0,
    sodiumMg: 227.0,
    waterG: 76.19,
  ),
  'seed_ee_borscht': SeedFoodComposition(
    source: SeedCompositionSource.fndds20172018,
    fdcId: 1103698,
    sourceDescription: 'Borscht',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 38.0,
    proteinG: 1.19,
    fatG: 1.81,
    carbohydrateByDifferenceG: 4.67,
    fiberG: 1.0,
    sodiumMg: 142.0,
    waterG: 91.47,
  ),
  'seed_ee_kasha': SeedFoodComposition(
    source: SeedCompositionSource.srLegacy2018,
    fdcId: 170686,
    sourceDescription: 'Buckwheat groats, roasted, cooked',
    match: SeedCompositionMatch.equivalent,
    note: null,
    energyKcal: 92.0,
    proteinG: 3.38,
    fatG: 0.62,
    carbohydrateByDifferenceG: 19.94,
    fiberG: 2.7,
    sodiumMg: 4.0,
    waterG: null,
  ),
};

/// Seed catalog foods with no defensible authoritative record; their
/// nutrient values are unknown.
const Map<String, String> seedFoodUnmatchedReasons = {
  'seed_oat_milk': 'No oat beverage in SR Legacy or FNDDS 2017-2018.',
  'seed_salad_garden':
      'No undressed garden-salad record in SR Legacy or FNDDS 2017-2018.',
  'seed_dumpling_pork':
      'The only FNDDS meat dumpling (1102083: 38% water, 22.7 g fat) describes a fried preparation, not boiled or steamed pork dumplings.',
  'seed_ramen_basic':
      'SR Legacy lists ramen only as dry soup mix; no cooked-noodle record.',
  'seed_cn_white_fungus': 'Tremella is not in SR Legacy or FNDDS 2017-2018.',
  'seed_cn_black_fungus':
      'SR Legacy lists wood ear only dried (Fungi, Cloud ears, dried); the catalog entry is the rehydrated food.',
  'seed_cn_hawthorn': 'Hawthorn fruit is not in SR Legacy or FNDDS 2017-2018.',
  'seed_cn_baozi': 'No steamed pork bun in SR Legacy or FNDDS 2017-2018.',
  'seed_cn_zongzi': 'No zongzi in SR Legacy or FNDDS 2017-2018.',
  'seed_cn_mooncake': 'No mooncake in SR Legacy or FNDDS 2017-2018.',
  'seed_cn_youcai':
      'Youcai (Brassica rapa oil-seed greens) has no SR Legacy or FNDDS record.',
  'seed_cn_chives':
      'SR Legacy chives are Allium schoenoprasum; Chinese chives are Allium tuberosum.',
  'seed_cn_black_rice': 'No black rice in SR Legacy or FNDDS 2017-2018.',
  'seed_cn_jiaozi_pork':
      'The only FNDDS meat dumpling (1102083) describes a fried preparation, not boiled jiaozi.',
  'seed_jp_nori':
      'SR Legacy lists laver only raw; the catalog entry is dried nori sheets.',
  'seed_jp_hijiki': 'Hijiki is not in SR Legacy or FNDDS 2017-2018.',
  'seed_jp_mochi': 'No mochi in SR Legacy or FNDDS 2017-2018.',
  'seed_jp_udon': 'No udon in SR Legacy or FNDDS 2017-2018.',
  'seed_jp_umeboshi': 'No umeboshi in SR Legacy or FNDDS 2017-2018.',
  'seed_jp_matcha': 'No matcha powder in SR Legacy or FNDDS 2017-2018.',
  'seed_kr_tteok':
      'FNDDS \'Rice cake\' (1101305) is the puffed snack, not tteok.',
  'seed_kr_gochujang': 'No gochujang in SR Legacy or FNDDS 2017-2018.',
  'seed_kr_doenjang': 'No doenjang in SR Legacy or FNDDS 2017-2018.',
  'seed_kr_japchae': 'No japchae in SR Legacy or FNDDS 2017-2018.',
  'seed_kr_kimbap': 'No kimbap in SR Legacy or FNDDS 2017-2018.',
  'seed_in_paneer':
      'SR Legacy and FNDDS 2017-2018 list paneer only inside palak paneer.',
  'seed_in_idli': 'No idli in SR Legacy or FNDDS 2017-2018.',
  'seed_in_chana_masala': 'No chickpea curry in SR Legacy or FNDDS 2017-2018.',
  'seed_in_raita': 'No raita in SR Legacy or FNDDS 2017-2018.',
  'seed_in_lassi': 'No lassi in SR Legacy or FNDDS 2017-2018.',
  'seed_in_tandoori_chicken':
      'No tandoori chicken in SR Legacy or FNDDS 2017-2018.',
  'seed_med_shakshuka': 'No shakshuka in SR Legacy or FNDDS 2017-2018.',
  'seed_sea_banh_mi': 'No banh mi in SR Legacy or FNDDS 2017-2018.',
  'seed_sea_satay': 'No satay in SR Legacy or FNDDS 2017-2018.',
  'seed_sea_nasi_goreng': 'FNDDS lists only Puerto Rican-style fried rice.',
  'seed_sea_rendang': 'No rendang in SR Legacy or FNDDS 2017-2018.',
  'seed_sea_laksa': 'No laksa in SR Legacy or FNDDS 2017-2018.',
  'seed_sea_tom_yum': 'No tom yum in SR Legacy or FNDDS 2017-2018.',
  'seed_ee_pelmeni':
      'The only FNDDS meat dumpling (1102083) describes a fried preparation, not boiled pelmeni.',
  'seed_ee_blini': 'No blini in SR Legacy or FNDDS 2017-2018.',
  'seed_mena_couscous_tagine':
      'No tagine dish in SR Legacy or FNDDS 2017-2018.',
  'seed_mena_harira': 'No harira in SR Legacy or FNDDS 2017-2018.',
  'seed_mena_shawarma_chicken':
      'No chicken shawarma in SR Legacy or FNDDS 2017-2018.',
  'seed_mena_kibbeh': 'No kibbeh in SR Legacy or FNDDS 2017-2018.',
};
